// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0 (the "License");

// Code generated by cmd_param_aliases; DO NOT EDIT.
// Source: internal/cli/param_concepts.json reduced against the live Cobra tree.
// Regenerate with `make generate-schema` (or `go generate ./internal/cli`).

package cli

// generatedParamAliases is the per-command parameter-alias table reduced from
// the reviewed concept dictionary. Each entry binds one runnable Cobra leaf.
var generatedParamAliases = []ParamAliasEntry{
	{
		CLIPath: "aitable +base-search",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "aitable +field-get",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +list-tables",
		Aliases: map[string]string{
			"base-id":    "base",
			"base-token": "base",
		},
	},
	{
		CLIPath: "aitable +record-query",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +record-share-url",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable +table-get",
		Aliases: map[string]string{
			"base":       "base-id",
			"base-token": "base-id",
		},
	},
	{
		CLIPath: "aitable record query",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "page"},
	},
	{
		CLIPath: "attendance +check-result",
		Blocked: []string{"user-id"},
	},
	{
		CLIPath: "attendance check result",
		Aliases: map[string]string{
			"user-ids": "users",
		},
		Blocked: []string{"at-user-ids", "staff-id", "uid", "user", "user-id", "userid"},
	},
	{
		CLIPath: "calendar event list",
		Aliases: map[string]string{
			"begin":           "start",
			"calendar":        "calendar-id",
			"date":            "start",
			"end-date":        "end",
			"end-time":        "end",
			"from":            "start",
			"from-date":       "start",
			"max-result":      "limit",
			"max-results":     "limit",
			"max-time":        "end",
			"min-time":        "start",
			"next-cursor":     "cursor",
			"next-page-token": "cursor",
			"next-token":      "cursor",
			"page-size":       "limit",
			"page-token":      "cursor",
			"per-page":        "limit",
			"since":           "start",
			"size":            "limit",
			"start-date":      "start",
			"start-time":      "start",
			"take":            "limit",
			"time-max":        "end",
			"time-min":        "start",
			"top":             "limit",
		},
		Blocked: []string{"offset", "page", "time"},
	},
	{
		CLIPath: "chat +group-members",
		Aliases: map[string]string{
			"group-name": "group",
		},
	},
	{
		CLIPath: "chat group members",
		Aliases: map[string]string{
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"group-id":             "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "group-ids", "name"},
	},
	{
		CLIPath: "chat group members add",
		Aliases: map[string]string{
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"group-id":             "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "group-ids", "name"},
	},
	{
		CLIPath: "chat group members remove",
		Aliases: map[string]string{
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"group-id":             "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "group-ids", "name"},
	},
	{
		CLIPath: "chat group rename",
		Aliases: map[string]string{
			"chat-id":              "id",
			"conversation-id":      "id",
			"group":                "id",
			"group-id":             "id",
			"open-conversation-id": "id",
		},
		Blocked: []string{"conversation-ids", "group-ids"},
	},
	{
		CLIPath:   "chat message add-emoji",
		Ambiguous: []string{"chat-id", "conversation-ids", "group-id", "open-conversation-id"},
	},
	{
		CLIPath:   "chat message add-text-emotion",
		Ambiguous: []string{"chat-id", "conversation-ids", "group-id", "open-conversation-id"},
	},
	{
		CLIPath: "chat message list",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"page-size":   "limit",
			"per-page":    "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "cursor", "page"},
	},
	{
		CLIPath: "chat message list-all",
		Aliases: map[string]string{
			"begin":      "start",
			"from":       "start",
			"from-date":  "start",
			"min-time":   "start",
			"since":      "start",
			"start-date": "start",
			"start-time": "start",
			"time-min":   "start",
		},
		Blocked: []string{"date", "time"},
	},
	{
		CLIPath: "chat message list-by-sender",
		Blocked: []string{"time"},
	},
	{
		CLIPath:   "chat message remove-emoji",
		Ambiguous: []string{"chat-id", "conversation-ids", "group-id", "open-conversation-id"},
	},
	{
		CLIPath:   "chat message remove-text-emotion",
		Ambiguous: []string{"chat-id", "conversation-ids", "group-id", "open-conversation-id"},
	},
	{
		CLIPath: "chat message send",
		Aliases: map[string]string{
			"to-user": "user",
		},
	},
	{
		CLIPath: "chat message send-by-bot",
		Aliases: map[string]string{
			"user-ids": "users",
		},
		Blocked:   []string{"staff-id", "uid", "user", "user-id", "userid"},
		Ambiguous: []string{"to-user-id"},
	},
	{
		CLIPath: "contact +dept-members",
		Aliases: map[string]string{
			"name":  "dept",
			"query": "dept",
		},
	},
	{
		CLIPath: "contact +list-dept-members",
		Aliases: map[string]string{
			"department-ids": "depts",
			"dept-ids":       "depts",
		},
		Blocked: []string{"department-id", "dept", "dept-id", "name", "query"},
	},
	{
		CLIPath: "contact +list-sub-depts",
		Aliases: map[string]string{
			"department":    "dept",
			"department-id": "dept",
			"dept-id":       "dept",
		},
		Blocked: []string{"department-ids", "dept-ids", "depts", "name", "parent", "query"},
	},
	{
		CLIPath: "contact +resolve-dept",
		Aliases: map[string]string{
			"query": "name",
		},
	},
	{
		CLIPath: "contact +search-user",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "contact dept list-children",
		Aliases: map[string]string{
			"department":    "dept",
			"department-id": "dept",
			"parent":        "dept",
			"parent-id":     "dept",
		},
		Blocked: []string{"department-ids", "depts", "name", "query"},
	},
	{
		CLIPath: "contact user profile get",
		Aliases: map[string]string{
			"id":      "staff-id",
			"ids":     "staff-id",
			"uid":     "staff-id",
			"user":    "staff-id",
			"user-id": "staff-id",
			"userid":  "staff-id",
		},
		Blocked: []string{"at-user-ids", "name", "to-user", "user-ids", "users"},
	},
	{
		CLIPath: "dev app get",
		Aliases: map[string]string{
			"app-id":         "unified-app-id",
			"application-id": "unified-app-id",
		},
		Blocked: []string{"agent-id", "app-secret"},
	},
	{
		CLIPath: "devdoc article search",
		Aliases: map[string]string{
			"current-page": "page",
			"limit":        "size",
			"max-result":   "size",
			"max-results":  "size",
			"page-no":      "page",
			"page-num":     "page",
			"page-size":    "size",
			"per-page":     "size",
			"take":         "size",
			"top":          "size",
		},
		Blocked: []string{"count", "cursor", "page-index", "page-token"},
	},
	{
		CLIPath: "ding +receiver-status",
		Aliases: map[string]string{
			"id": "ding-id",
		},
	},
	{
		CLIPath: "ding message receiver-status",
		Aliases: map[string]string{
			"id":           "ding-id",
			"open-ding-id": "ding-id",
		},
	},
	{
		CLIPath: "ding message send",
		Aliases: map[string]string{
			"robot": "robot-code",
		},
		Blocked: []string{"robot-id"},
	},
	{
		CLIPath: "doc +export-get",
		Blocked: []string{"node"},
	},
	{
		CLIPath: "doc +template-search",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "doc block delete",
		Blocked: []string{"index"},
	},
	{
		CLIPath: "doc block insert",
		Aliases: map[string]string{
			"body":    "text",
			"content": "text",
		},
		Blocked: []string{"before-block-id", "name", "title"},
	},
	{
		CLIPath: "doc block update",
		Aliases: map[string]string{
			"body":    "text",
			"content": "text",
		},
		Blocked: []string{"name", "title"},
	},
	{
		CLIPath: "drive info",
		Aliases: map[string]string{
			"space":        "space-id",
			"workspace":    "space-id",
			"workspace-id": "space-id",
		},
		Blocked: []string{"folder"},
	},
	{
		CLIPath: "drive list",
		Aliases: map[string]string{
			"folder-id": "folder",
		},
		Ambiguous: []string{"space"},
	},
	{
		CLIPath:   "drive upload",
		Ambiguous: []string{"space"},
	},
	{
		CLIPath: "mail +find-mail-user",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "mail folder update",
		Aliases: map[string]string{
			"folder":    "id",
			"folder-id": "id",
		},
		Blocked: []string{"space-id"},
	},
	{
		CLIPath: "mail message search",
		Aliases: map[string]string{
			"subject": "query",
		},
	},
	{
		CLIPath: "mail thread list",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"page-size":   "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "page"},
	},
	{
		CLIPath: "mail user search",
		Aliases: map[string]string{
			"keywords":    "keyword",
			"q":           "keyword",
			"query":       "keyword",
			"search-word": "keyword",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "oa +list-executed",
		Aliases: map[string]string{
			"max-result":  "limit",
			"max-results": "limit",
			"page-size":   "limit",
			"per-page":    "limit",
			"size":        "limit",
			"take":        "limit",
			"top":         "limit",
		},
		Blocked: []string{"count", "cursor"},
	},
	{
		CLIPath: "oa +search-forms",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "oa approval search-forms",
		Aliases: map[string]string{
			"keyword":     "query",
			"keywords":    "query",
			"q":           "query",
			"search-word": "query",
		},
		Blocked: []string{"name", "subject", "text", "title"},
	},
	{
		CLIPath: "report list",
		Aliases: map[string]string{
			"begin":      "start",
			"from":       "start",
			"from-date":  "start",
			"min-time":   "start",
			"since":      "start",
			"start-date": "start",
			"start-time": "start",
			"time-min":   "start",
		},
		Blocked: []string{"date", "time"},
	},
	{
		CLIPath: "report outbox list",
		Blocked: []string{"template-type"},
	},
}
