#!/usr/bin/env python3
"""Generate the release-hidden shortcut list from real test results.

Shortcuts whose latest real-backend result is not `real-ok` are kept in source
code but hidden from public discovery for this release.  The generated Go file
is a release gate; the Markdown/JSON files are the handoff list for the next
iteration.
"""

from __future__ import annotations

import datetime as dt
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
READ_PATH = ROOT / "docs" / "shortcut-real-read-results.json"
WRITE_PATH = ROOT / "docs" / "shortcut-real-write-results.json"
GO_PATH = ROOT / "internal" / "shortcut" / "release_hidden_generated.go"
MD_PATH = ROOT / "docs" / "shortcut-next-release-hidden.md"
JSON_PATH = ROOT / "docs" / "shortcut-next-release-hidden.json"


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def squish(text: str, limit: int = 180) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "…"


def error_text(row: dict[str, Any]) -> str:
    return f"{row.get('stderr') or ''}\n{row.get('stdout') or ''}"


def parse_error_payload(row: dict[str, Any]) -> dict[str, Any]:
    for key in ("stderr", "stdout"):
        raw = (row.get(key) or "").strip()
        if not raw:
            continue
        try:
            value = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            err = value.get("error")
            if isinstance(err, dict):
                return err
            return value
    return {}


def evidence(row: dict[str, Any]) -> str:
    payload = parse_error_payload(row)
    msg = payload.get("message")
    if isinstance(msg, str) and msg.strip():
        return squish(msg, 220)
    return squish(error_text(row), 220)


def collect() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for suite, path in (("read", READ_PATH), ("write", WRITE_PATH)):
        data = load(path)
        for row in data.get("results", []):
            if row.get("status") == "real-ok":
                continue
            out.append({
                "suite": suite,
                "service": row.get("service") or "",
                "command": row.get("command") or "",
                "risk": row.get("risk") or "",
                "status": row.get("status") or "",
                "failure_category": row.get("failure_category") or "unclassified",
                "fixability": row.get("fixability") or "",
                "diagnosis": row.get("diagnosis") or "",
                "evidence": evidence(row),
            })
    out.sort(key=lambda r: (r["suite"], r["service"], r["command"]))
    return out


def go_quote(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def write_go(rows: list[dict[str, Any]]) -> None:
    lines = [
        "// Code generated by scripts/gen_shortcut_release_hidden.py; DO NOT EDIT.",
        "",
        "package shortcut",
        "",
        "// releaseHiddenShortcuts contains shortcuts intentionally hidden from",
        "// public discovery in this release because their latest real-backend",
        "// test did not pass. The command implementations remain registered and",
        "// invocable by exact path for internal follow-up testing.",
        "var releaseHiddenShortcuts = map[string]string{",
    ]
    for row in rows:
        key = f"{row['service']}\x00{row['command']}"
        reason = (
            f"{row['suite']} real test not passed; "
            f"status={row['status']}; category={row['failure_category']}; "
            f"fixability={row['fixability'] or '-'}"
        )
        lines.append(f"\t{go_quote(key)}: {go_quote(reason)},")
    lines.extend(["}", ""])
    GO_PATH.write_text("\n".join(lines), encoding="utf-8")


def md_escape(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", "<br>")


def write_md(rows: list[dict[str, Any]]) -> None:
    generated = dt.datetime.now().isoformat(timespec="seconds")
    lines = [
        "# 本期隐藏、下期修复的 shortcut 清单",
        "",
        f"生成时间：`{generated}`",
        "",
        "来源：`docs/shortcut-real-read-results.json` 与 `docs/shortcut-real-write-results.json`。",
        "",
        "口径：最新真实后端测试结果不是 `real-ok` 的 shortcut，本期不对外 release；代码保留，并通过 `internal/shortcut/release_hidden_generated.go` 标记为 Hidden，后续补 fixture / 修后端 / 修 CLI 后再放开。",
        "",
        f"总计：{len(rows)} 条。",
        "",
        "| # | suite | shortcut | risk | status | category | fixability | 下期处理依据 |",
        "|---:|---|---|---|---|---|---|---|",
    ]
    for idx, row in enumerate(rows, 1):
        shortcut = f"{row['service']} {row['command']}"
        basis = row["diagnosis"] or row["evidence"]
        lines.append(
            f"| {idx} | {md_escape(row['suite'])} | `{md_escape(shortcut)}` | "
            f"{md_escape(row['risk'])} | {md_escape(row['status'])} | "
            f"{md_escape(row['failure_category'])} | {md_escape(row['fixability'])} | "
            f"{md_escape(squish(basis, 160))} |"
        )
    lines.append("")
    MD_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_json(rows: list[dict[str, Any]]) -> None:
    payload = {
        "generated_at": dt.datetime.now().isoformat(),
        "count": len(rows),
        "results": rows,
    }
    JSON_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    rows = collect()
    write_go(rows)
    write_md(rows)
    write_json(rows)
    print(f"hidden={len(rows)}")
    print(f"written: {GO_PATH}")
    print(f"written: {MD_PATH}")
    print(f"written: {JSON_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
